name: Generate Enhanced Sitemap

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight UTC

permissions:
  contents: write

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate base sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://adityapandey-dev.github.io/
          path-to-root: .
          include-html: true
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Enhance sitemap with page sections
        run: |
          python - <<EOF
          import xml.etree.ElementTree as ET
          import os
          from datetime import datetime
          
          # Define the sections you want to include
          sections = ["about", "skills", "education", "projects", "certifications", "contact"]
          
          # Parse the existing sitemap
          ns = {"ns": "http://www.sitemaps.org/schemas/sitemap/0.9"}
          tree = ET.parse('sitemap.xml')
          root = tree.getroot()
          
          # Get the main URL (homepage)
          main_url = None
          for url in root.findall('ns:url', ns):
            loc = url.find('ns:loc', ns)
            if loc is not None and (loc.text.endswith('index.html') or loc.text.endswith('/')):
              main_url = loc.text.rstrip('index.html')
              break
          
          if not main_url:
            main_url = "https://adityapandey-dev.github.io/"
          
          # Add section URLs
          today = datetime.now().strftime('%Y-%m-%d')
          
          for section in sections:
            section_url = ET.SubElement(root, '{http://www.sitemaps.org/schemas/sitemap/0.9}url')
            loc = ET.SubElement(section_url, '{http://www.sitemaps.org/schemas/sitemap/0.9}loc')
            loc.text = f"{main_url}#{section}"
            
            lastmod = ET.SubElement(section_url, '{http://www.sitemaps.org/schemas/sitemap/0.9}lastmod')
            lastmod.text = today
            
            changefreq = ET.SubElement(section_url, '{http://www.sitemaps.org/schemas/sitemap/0.9}changefreq')
            changefreq.text = "weekly"
            
            priority = ET.SubElement(section_url, '{http://www.sitemaps.org/schemas/sitemap/0.9}priority')
            priority.text = "0.7"
          
          # Write the enhanced sitemap
          tree.write('sitemap.xml', encoding='utf-8', xml_declaration=True)
          EOF

      - name: Commit and Push Sitemap
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add sitemap.xml
          git commit -m "Update enhanced sitemap with page sections" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/adityapandey-dev/adityapandey-dev.github.io.git

      - name: Notify Search Engines
        run: |
          curl "https://www.google.com/ping?sitemap=https://adityapandey-dev.github.io/sitemap.xml"
          curl "https://www.bing.com/webmaster/ping.aspx?siteMap=https://adityapandey-dev.github.io/sitemap.xml"
          curl "https://webmaster.yandex.com/ping?sitemap=https://adityapandey-dev.github.io/sitemap.xml"
