name: Generate Sitemap

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight UTC

permissions:
  contents: write

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://theadityapandey.github.io/
          path-to-root: .
          include-html: true

      - name: Commit and Push Sitemap
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add sitemap.xml
          git commit -m "Update sitemap" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/theadityapandey/theadityapandey.github.io.git

      - name: Notify Google of Updated Sitemap
        run: |
          curl "https://www.google.com/ping?sitemap=https://theadityapandey.github.io/sitemap.xml"
